package cisco_asa

type ShowAccessList struct {
	Entry_src_host          string `json:"ENTRY_SRC_HOST"`
	Entry_dst_fqdn          string `json:"ENTRY_DST_FQDN"`
	Entry_dst_range_start   string `json:"ENTRY_DST_RANGE_START"`
	Action                  string `json:"ACTION"`
	Log_level               string `json:"LOG_LEVEL"`
	Hit_count               string `json:"HIT_COUNT"`
	Line_hash               string `json:"LINE_HASH"`
	Entry_protocol_icmp     string `json:"ENTRY_PROTOCOL_ICMP"`
	Protocol                string `json:"PROTOCOL"`
	Dst_any                 string `json:"DST_ANY"`
	Dst_port_range_end      string `json:"DST_PORT_RANGE_END"`
	Entry_src_mask          string `json:"ENTRY_SRC_MASK"`
	Entry_dst_v6host        string `json:"ENTRY_DST_V6HOST"`
	Entry_port_range_start  string `json:"ENTRY_PORT_RANGE_START"`
	Src_object_grp          string `json:"SRC_OBJECT_GRP"`
	Dst_port                string `json:"DST_PORT"`
	Log_interval            string `json:"LOG_INTERVAL"`
	State                   string `json:"STATE"`
	Entry_src_v6mask        string `json:"ENTRY_SRC_V6MASK"`
	Entry_src_network       string `json:"ENTRY_SRC_NETWORK"`
	Entry_state             string `json:"ENTRY_STATE"`
	Dst_host                string `json:"DST_HOST"`
	Dst_network             string `json:"DST_NETWORK"`
	Dst_port_greater_than   string `json:"DST_PORT_GREATER_THAN"`
	Dst_port_grp            string `json:"DST_PORT_GRP"`
	Dst_port_object         string `json:"DST_PORT_OBJECT"`
	Acl_name_hash           string `json:"ACL_NAME_HASH"`
	Svc_object_grp          string `json:"SVC_OBJECT_GRP"`
	Src_intfc               string `json:"SRC_INTFC"`
	Src_v6mask              string `json:"SRC_V6MASK"`
	Entry_hash              string `json:"ENTRY_HASH"`
	Dst_object_grp          string `json:"DST_OBJECT_GRP"`
	Entry_src_v6network     string `json:"ENTRY_SRC_V6NETWORK"`
	Time_range              string `json:"TIME_RANGE"`
	Entry_dst_v6network     string `json:"ENTRY_DST_V6NETWORK"`
	Entry_port_range_end    string `json:"ENTRY_PORT_RANGE_END"`
	Acl_name                string `json:"ACL_NAME"`
	Remark                  string `json:"REMARK"`
	Dst_v6mask              string `json:"DST_V6MASK"`
	Entry_src_any           string `json:"ENTRY_SRC_ANY"`
	Entry_port_greater_than string `json:"ENTRY_PORT_GREATER_THAN"`
	Entry_dst_v6mask        string `json:"ENTRY_DST_V6MASK"`
	Acl_tot_elem            string `json:"ACL_TOT_ELEM"`
	Type                    string `json:"TYPE"`
	Src_network             string `json:"SRC_NETWORK"`
	Dst_v6host              string `json:"DST_V6HOST"`
	Entry_dst_host          string `json:"ENTRY_DST_HOST"`
	Entry_src_range_start   string `json:"ENTRY_SRC_RANGE_START"`
	Entry_src_range_end     string `json:"ENTRY_SRC_RANGE_END"`
	Entry_dst_network       string `json:"ENTRY_DST_NETWORK"`
	Line_num                string `json:"LINE_NUM"`
	Src_v6network           string `json:"SRC_V6NETWORK"`
	Dst_intfc               string `json:"DST_INTFC"`
	Dst_v6network           string `json:"DST_V6NETWORK"`
	Dst_mask                string `json:"DST_MASK"`
	Entry_hit_count         string `json:"ENTRY_HIT_COUNT"`
	Dst_port_range_start    string `json:"DST_PORT_RANGE_START"`
	Entry_dst_any           string `json:"ENTRY_DST_ANY"`
	Entry_icmp_type         string `json:"ENTRY_ICMP_TYPE"`
	Entry_protocol          string `json:"ENTRY_PROTOCOL"`
	Entry_src_fqdn          string `json:"ENTRY_SRC_FQDN"`
	Src_object              string `json:"SRC_OBJECT"`
	Dst_object              string `json:"DST_OBJECT"`
	Entry_icmp_code         string `json:"ENTRY_ICMP_CODE"`
	Src_host                string `json:"SRC_HOST"`
	Src_mask                string `json:"SRC_MASK"`
	Entry_dst_mask          string `json:"ENTRY_DST_MASK"`
	Entry_dst_fqdn_state    string `json:"ENTRY_DST_FQDN_STATE"`
	Svc_object              string `json:"SVC_OBJECT"`
	Src_v6host              string `json:"SRC_V6HOST"`
	Entry_port_less_than    string `json:"ENTRY_PORT_LESS_THAN"`
	Entry_dst_range_end     string `json:"ENTRY_DST_RANGE_END"`
	Entry_port              string `json:"ENTRY_PORT"`
	Src_any                 string `json:"SRC_ANY"`
	Dst_port_less_than      string `json:"DST_PORT_LESS_THAN"`
	Dst_icmp_type           string `json:"DST_ICMP_TYPE"`
	Entry_src_v6host        string `json:"ENTRY_SRC_V6HOST"`
	Entry_src_fqdn_state    string `json:"ENTRY_SRC_FQDN_STATE"`
}

var ShowAccessList_Template string = `Value Required ACL_NAME (\S+)
Value ACL_TOT_ELEM (\d+)
Value ACL_NAME_HASH (0x\w+)
Value TYPE (standard|extended)
Value LINE_NUM (\d+)
Value REMARK (.+?)
Value ACTION (permit|deny)
Value PROTOCOL ([a-z]+)
Value SVC_OBJECT_GRP (\S+)
Value SVC_OBJECT (\S+)
Value SRC_INTFC (\S+)
Value SRC_OBJECT_GRP (\S+)
Value SRC_OBJECT (\S+)
Value SRC_HOST (\d+\.\d+\.\d+\.\d+)
Value SRC_V6HOST ([0-9a-f:]+)
Value SRC_NETWORK (\d+\.\d+\.\d+\.\d+)
Value SRC_V6NETWORK ([0-9a-f:]+)
Value SRC_MASK (\d+\.\d+\.\d+\.\d+)
Value SRC_V6MASK (\d{1,3})
Value SRC_ANY (any[46]{0,1})
Value DST_INTFC (\S+)
Value DST_OBJECT_GRP (\S+)
Value DST_OBJECT (\S+)
Value DST_HOST (\d+\.\d+\.\d+\.\d+)
Value DST_V6HOST ([0-9a-f:]+)
Value DST_NETWORK (\d+\.\d+\.\d+\.\d+)
Value DST_V6NETWORK ([0-9a-f:]+)
Value DST_MASK (\d+\.\d+\.\d+\.\d+)
Value DST_V6MASK (\d{1,3})
Value DST_ANY (any[46]{0,1})
Value DST_PORT (\S+)
Value DST_PORT_LESS_THAN (\S+)
Value DST_PORT_GREATER_THAN (\S+)
Value DST_PORT_RANGE_START (\S+)
Value DST_PORT_RANGE_END (\S+)
Value DST_PORT_GRP (\S+)
Value DST_PORT_OBJECT (\S+)
Value DST_ICMP_TYPE ((?!log|time|inactive)\S+)
Value LOG_LEVEL ([a-z0-9]+)
Value LOG_INTERVAL (\d+)
Value TIME_RANGE (\S+)
Value STATE (inactive)
Value HIT_COUNT (\d+)
Value LINE_HASH (0x\w+)
Value ENTRY_PROTOCOL_ICMP (icmp)
Value ENTRY_PROTOCOL ([a-z\-]+)
Value ENTRY_SRC_FQDN (\S+)
Value ENTRY_SRC_RANGE_START (\d+\.\d+\.\d+\.\d+)
Value ENTRY_SRC_RANGE_END (\d+\.\d+\.\d+\.\d+)
Value ENTRY_SRC_HOST (\d+\.\d+\.\d+\.\d+)
Value ENTRY_SRC_V6HOST ([0-9a-f:]+)
Value ENTRY_SRC_NETWORK (\d+\.\d+\.\d+\.\d+)
Value ENTRY_SRC_V6NETWORK ([0-9a-f:]+)
Value ENTRY_SRC_MASK (\d+\.\d+\.\d+\.\d+)
Value ENTRY_SRC_V6MASK (\d{1,3})
Value ENTRY_SRC_ANY (any[46]{0,1})
Value ENTRY_SRC_FQDN_STATE (unresolved)
Value ENTRY_DST_FQDN (\S+)
Value ENTRY_DST_RANGE_START (\d+\.\d+\.\d+\.\d+)
Value ENTRY_DST_RANGE_END (\d+\.\d+\.\d+\.\d+)
Value ENTRY_DST_HOST (\S+)
Value ENTRY_DST_V6HOST ([0-9a-f:]+)
Value ENTRY_DST_NETWORK (\d+\.\d+\.\d+\.\d+)
Value ENTRY_DST_V6NETWORK ([0-9a-f:]+)
Value ENTRY_DST_MASK (\d+\.\d+\.\d+\.\d+)
Value ENTRY_DST_V6MASK (\d{1,3})
Value ENTRY_DST_ANY (any[46]{0,1})
Value ENTRY_DST_FQDN_STATE (unresolved)
Value ENTRY_ICMP_TYPE (alternate-address|conversion-error|echo|echo-reply|information-reply|information-request|mask-reply|mask-request|mobile-redirect|parameter-problem|redirect|router-advertisement|router-solicitation|source-quench|time-exceeded|timestamp-reply|timestamp-request|traceroute|unreachable|\d{1,3})
Value ENTRY_ICMP_CODE (\d+)
Value ENTRY_PORT ([a-z\-]+\s+\d+|[\w\-]+)
Value ENTRY_PORT_LESS_THAN ([a-z\-]+\s+\d+|\S+)
Value ENTRY_PORT_GREATER_THAN ([a-z\-]+\s+\d+|\S+)
Value ENTRY_PORT_RANGE_START ([a-z\-]+\s+\d+|\S+)
Value ENTRY_PORT_RANGE_END ([a-z\-]+\s+\d+|\S+)
Value ENTRY_HIT_COUNT (\d+)
Value ENTRY_STATE (inactive)
Value ENTRY_HASH (0x\w+)


Start
  ^access\-list\s+${ACL_NAME};\s+${ACL_TOT_ELEM}\s+elements;\s+name\s+hash:\s+${ACL_NAME_HASH}\s* -> Record
  ^access\-list\s+cached\s+ACL\s+log\s+flows.* -> NoRecord
  ^\s+alert-interval\s+\d+ -> NoRecord
  ^access\-list\s+${ACL_NAME}\s+line\s+${LINE_NUM}\s+remark\s+${REMARK}\s*$$ -> Record
  ^access\-list\s+${ACL_NAME}\s+line\s+${LINE_NUM}\s+${TYPE}\s+${ACTION}\s+(object\-group\s+${SVC_OBJECT_GRP}|object\s+${SVC_OBJECT}|${PROTOCOL})\s+(interface\s+${SRC_INTFC}|object\-group\s+${SRC_OBJECT_GRP}|object\s+${SRC_OBJECT}|host\s+(${SRC_HOST}|${SRC_V6HOST})|${SRC_NETWORK}\s+${SRC_MASK}|${SRC_V6NETWORK}\/${SRC_V6MASK}|${SRC_ANY})\s+(interface\s+${DST_INTFC}|object\-group\s+${DST_OBJECT_GRP}|object\s+${DST_OBJECT}|host\s+(${DST_HOST}|${DST_V6HOST})|${DST_NETWORK}\s+${DST_MASK}|${DST_V6NETWORK}\/${DST_V6MASK}|${DST_ANY})\s+((eq\s+${DST_PORT}|lt\s+${DST_PORT_LESS_THAN}|gt\s+${DST_PORT_GREATER_THAN}|range\s+${DST_PORT_RANGE_START}\s+${DST_PORT_RANGE_END}|object\-group\s+${DST_PORT_GRP}|object\s+${DST_PORT_OBJECT})\s+){0,1}(${ENTRY_ICMP_TYPE}(\s+${ENTRY_ICMP_CODE}){0,1}\s+){0,1}((log\s+(${LOG_LEVEL}\s+interval\s+${LOG_INTERVAL}|disable|default))\s+){0,1}(time-range\s+${TIME_RANGE}\s+){0,1}(${STATE}\s+){0,1}\(hitcnt=${HIT_COUNT}\)\s+(\(inactive\)\s+){0,1}${LINE_HASH}\s* -> Record
  ^\s+access\-list\s+${ACL_NAME}\s+line\s+${LINE_NUM}\s+${TYPE}\s+${ACTION}\s+${ENTRY_PROTOCOL_ICMP}\s+(fqdn\s+${ENTRY_SRC_FQDN}|range\s+${ENTRY_SRC_RANGE_START}\s+${ENTRY_SRC_RANGE_END}|host\s+(${ENTRY_SRC_HOST}|${ENTRY_SRC_V6HOST})|${ENTRY_SRC_NETWORK}\s+${ENTRY_SRC_MASK}|${ENTRY_SRC_V6NETWORK}\/${ENTRY_SRC_V6MASK}|${ENTRY_SRC_ANY})\s+(\(${ENTRY_SRC_FQDN_STATE}\)\s+){0,1}(fqdn\s+${ENTRY_DST_FQDN}|range\s+${ENTRY_DST_RANGE_START}\s+${ENTRY_DST_RANGE_END}|host\s+(${ENTRY_DST_HOST}|${ENTRY_DST_V6HOST})|${ENTRY_DST_NETWORK}\s+${ENTRY_DST_MASK}|${ENTRY_DST_V6NETWORK}\/${ENTRY_DST_V6MASK}|${ENTRY_DST_ANY})\s+(\(${ENTRY_DST_FQDN_STATE}\)\s+){0,1}(${ENTRY_ICMP_TYPE}(\s+${ENTRY_ICMP_CODE}){0,1}\s+){0,1}(log\s+(${LOG_LEVEL}\s+interval\s+${LOG_INTERVAL}|disable|default)\s+){0,1}(time-range\s+${TIME_RANGE}\s+){0,1}(inactive){0,1}\s*(\(hitcnt=${ENTRY_HIT_COUNT}\)){0,1}\s*(\(${ENTRY_STATE}\)){0,1}\s+${ENTRY_HASH}\s* -> Record
  ^\s*access\-list\s+${ACL_NAME}\s+line\s+${LINE_NUM}\s+${TYPE}\s+${ACTION}\s+(${ENTRY_PROTOCOL}\s+){0,1}(fqdn\s+${ENTRY_SRC_FQDN}|range\s+${ENTRY_SRC_RANGE_START}\s+${ENTRY_SRC_RANGE_END}|host\s+(${ENTRY_SRC_HOST}|${ENTRY_SRC_V6HOST})|${ENTRY_SRC_NETWORK}\s+${ENTRY_SRC_MASK}|${ENTRY_SRC_V6NETWORK}\/${ENTRY_SRC_V6MASK}|${ENTRY_SRC_ANY})\s+(\(${ENTRY_SRC_FQDN_STATE}\)\s+){0,1}((fqdn\s+${ENTRY_DST_FQDN}|range\s+${ENTRY_DST_RANGE_START}\s+${ENTRY_DST_RANGE_END}|host\s+(${ENTRY_DST_HOST}|${ENTRY_DST_V6HOST})|${ENTRY_DST_NETWORK}\s+${ENTRY_DST_MASK}|${ENTRY_DST_V6NETWORK}\/${ENTRY_DST_V6MASK}|${ENTRY_DST_ANY})\s+){0,1}(\(${ENTRY_DST_FQDN_STATE}\)\s+){0,1}((eq\s+${ENTRY_PORT}|lt\s+${ENTRY_PORT_LESS_THAN}|gt\s+${ENTRY_PORT_GREATER_THAN}|range\s+${ENTRY_PORT_RANGE_START}\s+${ENTRY_PORT_RANGE_END})\s+){0,1}(log\s+([a-z0-9]+\s+interval\s+\d+|disable|default)\s+){0,1}(time-range\s+${TIME_RANGE}\s+){0,1}(inactive){0,1}\s*(\(hitcnt=${ENTRY_HIT_COUNT}\)){0,1}\s*(\(${ENTRY_STATE}\)){0,1}\s+${ENTRY_HASH}\s* -> Record
  ^.* -> Error "Did not match any rules"

EOF
`
