package models

type ArubaAoscxShowInterfaceDomDetail struct {
	Interface	string	`json:"INTERFACE"`
	Iface_type	string	`json:"IFACE_TYPE"`
	Channel	[]string	`json:"CHANNEL"`
	Temperature	string	`json:"TEMPERATURE"`
	Temp_high_alarm_trig	string	`json:"TEMP_HIGH_ALARM_TRIG"`
	Temp_low_alarm_trig	string	`json:"TEMP_LOW_ALARM_TRIG"`
	Temp_high_warn_trig	string	`json:"TEMP_HIGH_WARN_TRIG"`
	Temp_low_warn_trig	string	`json:"TEMP_LOW_WARN_TRIG"`
	Temp_high_alarm_threshold	string	`json:"TEMP_HIGH_ALARM_THRESHOLD"`
	Temp_low_alarm_threshold	string	`json:"TEMP_LOW_ALARM_THRESHOLD"`
	Temp_high_warn_threshold	string	`json:"TEMP_HIGH_WARN_THRESHOLD"`
	Temp_low_warn_threshold	string	`json:"TEMP_LOW_WARN_THRESHOLD"`
	Voltage	string	`json:"VOLTAGE"`
	Volt_high_alarm_trig	string	`json:"VOLT_HIGH_ALARM_TRIG"`
	Volt_low_alarm_trig	string	`json:"VOLT_LOW_ALARM_TRIG"`
	Volt_high_warn_trig	string	`json:"VOLT_HIGH_WARN_TRIG"`
	Volt_low_warn_trig	string	`json:"VOLT_LOW_WARN_TRIG"`
	Volt_high_alarm_threshold	string	`json:"VOLT_HIGH_ALARM_THRESHOLD"`
	Volt_low_alarm_threshold	string	`json:"VOLT_LOW_ALARM_THRESHOLD"`
	Volt_high_warn_threshold	string	`json:"VOLT_HIGH_WARN_THRESHOLD"`
	Volt_low_warn_threshold	string	`json:"VOLT_LOW_WARN_THRESHOLD"`
	Tx_bias	[]string	`json:"TX_BIAS"`
	Tx_bias_high_alarm_trig	[]string	`json:"TX_BIAS_HIGH_ALARM_TRIG"`
	Tx_bias_low_alarm_trig	[]string	`json:"TX_BIAS_LOW_ALARM_TRIG"`
	Tx_bias_high_warn_trig	[]string	`json:"TX_BIAS_HIGH_WARN_TRIG"`
	Tx_bias_low_warn_trig	[]string	`json:"TX_BIAS_LOW_WARN_TRIG"`
	Tx_bias_high_alarm_threshold	[]string	`json:"TX_BIAS_HIGH_ALARM_THRESHOLD"`
	Tx_bias_low_alarm_threshold	[]string	`json:"TX_BIAS_LOW_ALARM_THRESHOLD"`
	Tx_bias_high_warn_threshold	[]string	`json:"TX_BIAS_HIGH_WARN_THRESHOLD"`
	Tx_bias_low_warn_threshold	[]string	`json:"TX_BIAS_LOW_WARN_THRESHOLD"`
	Rx_mw	[]string	`json:"RX_MW"`
	Rx_high_alarm_trig	[]string	`json:"RX_HIGH_ALARM_TRIG"`
	Rx_low_alarm_trig	[]string	`json:"RX_LOW_ALARM_TRIG"`
	Rx_high_warn_trig	[]string	`json:"RX_HIGH_WARN_TRIG"`
	Rx_low_warn_trig	[]string	`json:"RX_LOW_WARN_TRIG"`
	Rx_high_alarm_threshold	[]string	`json:"RX_HIGH_ALARM_THRESHOLD"`
	Rx_low_alarm_threshold	[]string	`json:"RX_LOW_ALARM_THRESHOLD"`
	Rx_high_warn_threshold	[]string	`json:"RX_HIGH_WARN_THRESHOLD"`
	Rx_low_warn_threshold	[]string	`json:"RX_LOW_WARN_THRESHOLD"`
	Tx_mw	[]string	`json:"TX_MW"`
	Tx_high_alarm_trig	[]string	`json:"TX_HIGH_ALARM_TRIG"`
	Tx_low_alarm_trig	[]string	`json:"TX_LOW_ALARM_TRIG"`
	Tx_high_warn_trig	[]string	`json:"TX_HIGH_WARN_TRIG"`
	Tx_low_warn_trig	[]string	`json:"TX_LOW_WARN_TRIG"`
	Tx_high_alarm_threshold	[]string	`json:"TX_HIGH_ALARM_THRESHOLD"`
	Tx_low_alarm_threshold	[]string	`json:"TX_LOW_ALARM_THRESHOLD"`
	Tx_high_warn_threshold	[]string	`json:"TX_HIGH_WARN_THRESHOLD"`
	Tx_low_warn_threshold	[]string	`json:"TX_LOW_WARN_THRESHOLD"`
}