package models

type BrocadeFastironShowInterfaces struct {
	Interface	string	`json:"interface"`
	Intstate	string	`json:"intstate"`
	Protostate	string	`json:"protostate"`
	Stprootguard	string	`json:"stprootguard"`
	Stpbpduguard	string	`json:"stpbpduguard"`
	Hardwaretype	string	`json:"hardwaretype"`
	Mac	string	`json:"mac"`
	Bia	string	`json:"bia"`
	Confspeed	string	`json:"confspeed"`
	Confduplex	string	`json:"confduplex"`
	Actualspeed	string	`json:"actualspeed"`
	Actualduplex	string	`json:"actualduplex"`
	L2portstate	string	`json:"l2portstate"`
	L2portmode	string	`json:"l2portmode"`
	Untaggedvlan	string	`json:"untaggedvlan"`
	Numtaggedvlans	string	`json:"numtaggedvlans"`
	Stpconfstate	string	`json:"stpconfstate"`
	Priority	string	`json:"priority"`
	Flowcontrolconfigstate	string	`json:"flowcontrolconfigstate"`
	Flowcontrolopstate	string	`json:"flowcontrolopstate"`
	Flowcontrolnegconfig	string	`json:"flowcontrolnegconfig"`
	Mirrorstate	string	`json:"mirrorstate"`
	Monitorstate	string	`json:"monitorstate"`
	Activelagports	string	`json:"activelagports"`
	Activelagrole	string	`json:"activelagrole"`
	Activelagprimaryport	string	`json:"activelagprimaryport"`
	Conflagports	string	`json:"conflagports"`
	Conflagrole	string	`json:"conflagrole"`
	Conflagprimaryport	string	`json:"conflagprimaryport"`
	Portname	string	`json:"portname"`
	L2mtubytes	string	`json:"l2mtubytes"`
	Loadinterval	string	`json:"loadinterval"`
	Inputbitssec	string	`json:"inputbitssec"`
	Inputpacketssec	string	`json:"inputpacketssec"`
	Inputpercentutilization	string	`json:"inputpercentutilization"`
	Outputbitssec	string	`json:"outputbitssec"`
	Outputpacketssec	string	`json:"outputpacketssec"`
	Outputpercentutilization	string	`json:"outputpercentutilization"`
	Inputpacketstotal	string	`json:"inputpacketstotal"`
	Inputbytestotal	string	`json:"inputbytestotal"`
	Inputnobuffers	string	`json:"inputnobuffers"`
	Inputbroadcasts	string	`json:"inputbroadcasts"`
	Inputmulticasts	string	`json:"inputmulticasts"`
	Inputunicasts	string	`json:"inputunicasts"`
	Inputerrors	string	`json:"inputerrors"`
	Inputcrcerrors	string	`json:"inputcrcerrors"`
	Inputframeerrors	string	`json:"inputframeerrors"`
	Inputignorederrors	string	`json:"inputignorederrors"`
	Inputrunts	string	`json:"inputrunts"`
	Inputgiants	string	`json:"inputgiants"`
	Outputpacketstotal	string	`json:"outputpacketstotal"`
	Outputbytestotal	string	`json:"outputbytestotal"`
	Outputunderruns	string	`json:"outputunderruns"`
	Outputbroadcasts	string	`json:"outputbroadcasts"`
	Outputmulticasts	string	`json:"outputmulticasts"`
	Outputunicasts	string	`json:"outputunicasts"`
	Outputerrors	string	`json:"outputerrors"`
	Outputcollisions	string	`json:"outputcollisions"`
	Relayagentinfo	string	`json:"relayagentinfo"`
	Queue0queued	string	`json:"queue0queued"`
	Queue0dropped	string	`json:"queue0dropped"`
	Queue1queued	string	`json:"queue1queued"`
	Queue1dropped	string	`json:"queue1dropped"`
	Queue2queued	string	`json:"queue2queued"`
	Queue2dropped	string	`json:"queue2dropped"`
	Queue3queued	string	`json:"queue3queued"`
	Queue3dropped	string	`json:"queue3dropped"`
	Queue4queued	string	`json:"queue4queued"`
	Queue4dropped	string	`json:"queue4dropped"`
	Queue5queued	string	`json:"queue5queued"`
	Queue5dropped	string	`json:"queue5dropped"`
	Queue6queued	string	`json:"queue6queued"`
	Queue6dropped	string	`json:"queue6dropped"`
	Queue7queued	string	`json:"queue7queued"`
	Queue7dropped	string	`json:"queue7dropped"`
}