package models

type BrocadeNetironShowInterfaces struct {
	Interface	string	`json:"interface"`
	Intstate	string	`json:"intstate"`
	Protostate	string	`json:"protostate"`
	Stprootguard	string	`json:"stprootguard"`
	Stpbpduguard	string	`json:"stpbpduguard"`
	Hardwaretype	string	`json:"hardwaretype"`
	Mac	string	`json:"mac"`
	Bia	string	`json:"bia"`
	Conffiberspeed	string	`json:"conffiberspeed"`
	Confcopperspeed	string	`json:"confcopperspeed"`
	Conffiberduplex	string	`json:"conffiberduplex"`
	Confcopperduplex	string	`json:"confcopperduplex"`
	Actualspeed	string	`json:"actualspeed"`
	Actualduplex	string	`json:"actualduplex"`
	L2portstate	string	`json:"l2portstate"`
	L2portmode	string	`json:"l2portmode"`
	Untaggedvlan	string	`json:"untaggedvlan"`
	Numtaggedvlans	string	`json:"numtaggedvlans"`
	Stpconfstate	string	`json:"stpconfstate"`
	Priority	string	`json:"priority"`
	Flowcontrolstate	string	`json:"flowcontrolstate"`
	Priorityforcedstate	string	`json:"priorityforcedstate"`
	Dropprecedencelevel	string	`json:"dropprecedencelevel"`
	Dropprecedenceforcestate	string	`json:"dropprecedenceforcestate"`
	Dhcpsnooptrust	string	`json:"dhcpsnooptrust"`
	Mirrorstate	string	`json:"mirrorstate"`
	Monitorstate	string	`json:"monitorstate"`
	Lacpbpduforward	string	`json:"lacpbpduforward"`
	Lldpbpduforward	string	`json:"lldpbpduforward"`
	Activelagports	string	`json:"activelagports"`
	Activelagrole	string	`json:"activelagrole"`
	Activelagprimaryport	string	`json:"activelagprimaryport"`
	Conflagports	string	`json:"conflagports"`
	Conflagrole	string	`json:"conflagrole"`
	Conflagprimaryport	string	`json:"conflagprimaryport"`
	Portname	string	`json:"portname"`
	L2mtubytes	string	`json:"l2mtubytes"`
	Encapsulation	string	`json:"encapsulation"`
	Openflowopstate	string	`json:"openflowopstate"`
	Openflowindex	string	`json:"openflowindex"`
	Clusterl2protoforwarding	string	`json:"clusterl2protoforwarding"`
	Loadinterval	string	`json:"loadinterval"`
	Inputbitssec	string	`json:"inputbitssec"`
	Inputpacketssec	string	`json:"inputpacketssec"`
	Inputpercentutilization	string	`json:"inputpercentutilization"`
	Outputbitssec	string	`json:"outputbitssec"`
	Outputpacketssec	string	`json:"outputpacketssec"`
	Outputpercentutilization	string	`json:"outputpercentutilization"`
	Inputpacketstotal	string	`json:"inputpacketstotal"`
	Inputbytestotal	string	`json:"inputbytestotal"`
	Inputnobuffers	string	`json:"inputnobuffers"`
	Inputbroadcasts	string	`json:"inputbroadcasts"`
	Inputmulticasts	string	`json:"inputmulticasts"`
	Inputunicasts	string	`json:"inputunicasts"`
	Inputerrors	string	`json:"inputerrors"`
	Inputcrcerrors	string	`json:"inputcrcerrors"`
	Inputframeerrors	string	`json:"inputframeerrors"`
	Inputignorederrors	string	`json:"inputignorederrors"`
	Inputrunts	string	`json:"inputrunts"`
	Inputgiants	string	`json:"inputgiants"`
	Inputnpreceivedpackets	string	`json:"inputnpreceivedpackets"`
	Inputsenttotmpackets	string	`json:"inputsenttotmpackets"`
	Inputnpingressdroppedpackets	string	`json:"inputnpingressdroppedpackets"`
	Outputpacketstotal	string	`json:"outputpacketstotal"`
	Outputbytestotal	string	`json:"outputbytestotal"`
	Outputunderruns	string	`json:"outputunderruns"`
	Outputbroadcasts	string	`json:"outputbroadcasts"`
	Outputmulticasts	string	`json:"outputmulticasts"`
	Outputunicasts	string	`json:"outputunicasts"`
	Outputerrors	string	`json:"outputerrors"`
	Outputcollisions	string	`json:"outputcollisions"`
	Outputnptransmittedpackets	string	`json:"outputnptransmittedpackets"`
	Outputreceivedfromtmpackets	string	`json:"outputreceivedfromtmpackets"`
	L3mtubytes	string	`json:"l3mtubytes"`
	Ipaddress	string	`json:"ipaddress"`
	Ipencapsulation	string	`json:"ipencapsulation"`
}