package models

type CiscoAsaShowAspDrop struct {
	Flow_drop_acl_drop	string	`json:"FLOW_DROP_ACL_DROP"`
	Flow_drop_shunned	string	`json:"FLOW_DROP_SHUNNED"`
	Flow_drop_cluster_redirect	string	`json:"FLOW_DROP_CLUSTER_REDIRECT"`
	Flow_drop_inspect_fail	string	`json:"FLOW_DROP_INSPECT_FAIL"`
	Flow_drop_ipsec_selector_failure	string	`json:"FLOW_DROP_IPSEC_SELECTOR_FAILURE"`
	Flow_drop_nat_rpf_failed	string	`json:"FLOW_DROP_NAT_RPF_FAILED"`
	Flow_drop_out_of_memory	string	`json:"FLOW_DROP_OUT_OF_MEMORY"`
	Flow_drop_ssl_bad_record_detect	string	`json:"FLOW_DROP_SSL_BAD_RECORD_DETECT"`
	Flow_drop_ssl_handshake_failed	string	`json:"FLOW_DROP_SSL_HANDSHAKE_FAILED"`
	Flow_drop_vpn_overlap_conflict	string	`json:"FLOW_DROP_VPN_OVERLAP_CONFLICT"`
	Flow_drop_vpn_missing_decrypt	string	`json:"FLOW_DROP_VPN_MISSING_DECRYPT"`
	Flow_drop_svc_replacement_conn	string	`json:"FLOW_DROP_SVC_REPLACEMENT_CONN"`
	Flow_drop_svc_selector_failure	string	`json:"FLOW_DROP_SVC_SELECTOR_FAILURE"`
	Flow_drop_svc_failover	string	`json:"FLOW_DROP_SVC_FAILOVER"`
	Flow_drop_ssl_record_decrypt_error	string	`json:"FLOW_DROP_SSL_RECORD_DECRYPT_ERROR"`
	Flow_drop_ctm_crypto_request_error	string	`json:"FLOW_DROP_CTM_CRYPTO_REQUEST_ERROR"`
	Flow_drop_vpn_handle_not_found	string	`json:"FLOW_DROP_VPN_HANDLE_NOT_FOUND"`
	Flow_drop_np_socket_data_move_failure	string	`json:"FLOW_DROP_NP_SOCKET_DATA_MOVE_FAILURE"`
	Flow_drop_dtls_hello_close	string	`json:"FLOW_DROP_DTLS_HELLO_CLOSE"`
	Flow_last_cleared	string	`json:"FLOW_LAST_CLEARED"`
	Acl_drop	string	`json:"ACL_DROP"`
	Async_lock_queue_limit	string	`json:"ASYNC_LOCK_QUEUE_LIMIT"`
	Bad_ipsec_natt	string	`json:"BAD_IPSEC_NATT"`
	Bad_tcp_cksum	string	`json:"BAD_TCP_CKSUM"`
	Bad_tcp_flags	string	`json:"BAD_TCP_FLAGS"`
	Cluster_bad_trailer	string	`json:"CLUSTER_BAD_TRAILER"`
	Cluster_ccl_backup	string	`json:"CLUSTER_CCL_BACKUP"`
	Cluster_ccl_unknown	string	`json:"CLUSTER_CCL_UNKNOWN"`
	Cluster_ccl_unknown_stub	string	`json:"CLUSTER_CCL_UNKNOWN_STUB"`
	Cluster_non_ip_pkt	string	`json:"CLUSTER_NON_IP_PKT"`
	Conn_limit	string	`json:"CONN_LIMIT"`
	Connection_lock	string	`json:"CONNECTION_LOCK"`
	Cp_event_queue_error	string	`json:"CP_EVENT_QUEUE_ERROR"`
	Cp_syslog_event_queue_error	string	`json:"CP_SYSLOG_EVENT_QUEUE_ERROR"`
	Ctm_error	string	`json:"CTM_ERROR"`
	Dispatch_queue_limit	string	`json:"DISPATCH_QUEUE_LIMIT"`
	Dispatch_block_alloc	string	`json:"DISPATCH_BLOCK_ALLOC"`
	Flow_being_freed	string	`json:"FLOW_BEING_FREED"`
	Flow_expired	string	`json:"FLOW_EXPIRED"`
	Fo_standby	string	`json:"FO_STANDBY"`
	Fragment_reassembly_failed	string	`json:"FRAGMENT_REASSEMBLY_FAILED"`
	Host_limit	string	`json:"HOST_LIMIT"`
	Ifc_classify	string	`json:"IFC_CLASSIFY"`
	Inspect_dns_id_not_matched	string	`json:"INSPECT_DNS_ID_NOT_MATCHED"`
	Inspect_dns_invalid_domain_label	string	`json:"INSPECT_DNS_INVALID_DOMAIN_LABEL"`
	Inspect_dns_invalid_pak	string	`json:"INSPECT_DNS_INVALID_PAK"`
	Inspect_dns_pak_too_long	string	`json:"INSPECT_DNS_PAK_TOO_LONG"`
	Inspect_dp_out_of_memory	string	`json:"INSPECT_DP_OUT_OF_MEMORY"`
	Inspect_icmp_bad_code	string	`json:"INSPECT_ICMP_BAD_CODE"`
	Inspect_icmp_error_no_existing_conn	string	`json:"INSPECT_ICMP_ERROR_NO_EXISTING_CONN"`
	Inspect_icmp_invalid_pak	string	`json:"INSPECT_ICMP_INVALID_PAK"`
	Inspect_icmp_seq_num_not_matched	string	`json:"INSPECT_ICMP_SEQ_NUM_NOT_MATCHED"`
	Intercept_unexpected	string	`json:"INTERCEPT_UNEXPECTED"`
	Interface_down	string	`json:"INTERFACE_DOWN"`
	Invalid_encap	string	`json:"INVALID_ENCAP"`
	Invalid_ip_header	string	`json:"INVALID_IP_HEADER"`
	Invalid_ip_length	string	`json:"INVALID_IP_LENGTH"`
	Invalid_ip_option	string	`json:"INVALID_IP_OPTION"`
	Invalid_tcp_hdr_length	string	`json:"INVALID_TCP_HDR_LENGTH"`
	Invalid_udp_length	string	`json:"INVALID_UDP_LENGTH"`
	Ipsec_tun_down	string	`json:"IPSEC_TUN_DOWN"`
	L2_acl	string	`json:"L2_ACL"`
	Last_cleared	string	`json:"LAST_CLEARED"`
	Lu_invalid_pkt	string	`json:"LU_INVALID_PKT"`
	Mcast_in_nonactive_device	string	`json:"MCAST_IN_NONACTIVE_DEVICE"`
	Mp_svc_bad_length	string	`json:"MP_SVC_BAD_LENGTH"`
	Mp_svc_flow_control	string	`json:"MP_SVC_FLOW_CONTROL"`
	Mp_svc_no_channel	string	`json:"MP_SVC_NO_CHANNEL"`
	Mp_svc_no_fragment	string	`json:"MP_SVC_NO_FRAGMENT"`
	Mp_svc_no_session	string	`json:"MP_SVC_NO_SESSION"`
	Nat_failed	string	`json:"NAT_FAILED"`
	Nat_no_xlate_to_pat_pool	string	`json:"NAT_NO_XLATE_TO_PAT_POOL"`
	Nat_xlate_failed	string	`json:"NAT_XLATE_FAILED"`
	Natt_keepalive	string	`json:"NATT_KEEPALIVE"`
	No_adjacency	string	`json:"NO_ADJACENCY"`
	No_inspect	string	`json:"NO_INSPECT"`
	No_route	string	`json:"NO_ROUTE"`
	Np_socket_closed	string	`json:"NP_SOCKET_CLOSED"`
	Np_socket_lock_failure	string	`json:"NP_SOCKET_LOCK_FAILURE"`
	Np_sp_invalid_spi	string	`json:"NP_SP_INVALID_SPI"`
	Object_group_search_threshold_exceeded	string	`json:"OBJECT_GROUP_SEARCH_THRESHOLD_EXCEEDED"`
	Punt_queue_limit	string	`json:"PUNT_QUEUE_LIMIT"`
	Punt_limit	string	`json:"PUNT_LIMIT"`
	Punt_no_mem	string	`json:"PUNT_NO_MEM"`
	Punt_rate_limit	string	`json:"PUNT_RATE_LIMIT"`
	Rm_conn_rate_limit	string	`json:"RM_CONN_RATE_LIMIT"`
	Rm_inspect_rate_limit	string	`json:"RM_INSPECT_RATE_LIMIT"`
	Rpf_violated	string	`json:"RPF_VIOLATED"`
	Rule_transaction_in_progress	string	`json:"RULE_TRANSACTION_IN_PROGRESS"`
	Security_failed	string	`json:"SECURITY_FAILED"`
	Shunned	string	`json:"SHUNNED"`
	Sp_security_failed	string	`json:"SP_SECURITY_FAILED"`
	Ssl_first_record_invalid	string	`json:"SSL_FIRST_RECORD_INVALID"`
	Tcp_3whs_failed	string	`json:"TCP_3WHS_FAILED"`
	Tcp_ack_syn_diff	string	`json:"TCP_ACK_SYN_DIFF"`
	Tcp_bad_option_list	string	`json:"TCP_BAD_OPTION_LIST"`
	Tcp_buffer_full	string	`json:"TCP_BUFFER_FULL"`
	Tcp_buffer_timeout	string	`json:"TCP_BUFFER_TIMEOUT"`
	Tcp_conn_limit	string	`json:"TCP_CONN_LIMIT"`
	Tcp_data_past_fin	string	`json:"TCP_DATA_PAST_FIN"`
	Tcp_dual_open	string	`json:"TCP_DUAL_OPEN"`
	Tcp_dup_in_queue	string	`json:"TCP_DUP_IN_QUEUE"`
	Tcp_fo_drop	string	`json:"TCP_FO_DROP"`
	Tcp_global_buffer_full	string	`json:"TCP_GLOBAL_BUFFER_FULL"`
	Tcp_invalid_ack	string	`json:"TCP_INVALID_ACK"`
	Tcp_not_syn	string	`json:"TCP_NOT_SYN"`
	Tcp_paws_fail	string	`json:"TCP_PAWS_FAIL"`
	Tcp_rst_syn_in_win	string	`json:"TCP_RST_SYN_IN_WIN"`
	Tcp_rstfin_ooo	string	`json:"TCP_RSTFIN_OOO"`
	Tcp_seq_past_win	string	`json:"TCP_SEQ_PAST_WIN"`
	Tcp_seq_syn_diff	string	`json:"TCP_SEQ_SYN_DIFF"`
	Tcp_synack_ooo	string	`json:"TCP_SYNACK_OOO"`
	Ttl_exceeded	string	`json:"TTL_EXCEEDED"`
	Unable_to_add_flow	string	`json:"UNABLE_TO_ADD_FLOW"`
	Unable_to_create_flow	string	`json:"UNABLE_TO_CREATE_FLOW"`
	Unsupported_ip_version	string	`json:"UNSUPPORTED_IP_VERSION"`
}