package models

type CiscoNxosShowIpBgpNeighbors struct {
	Neighbor	string	`json:"NEIGHBOR"`
	Peer_group	string	`json:"PEER_GROUP"`
	Description	string	`json:"DESCRIPTION"`
	Vrf	string	`json:"VRF"`
	Asn	string	`json:"ASN"`
	Remote_asn	string	`json:"REMOTE_ASN"`
	Local_asn	string	`json:"LOCAL_ASN"`
	Bgp_state	string	`json:"BGP_STATE"`
	Uptime	string	`json:"UPTIME"`
	Source_iface	string	`json:"SOURCE_IFACE"`
	Conn_estab	string	`json:"CONN_ESTAB"`
	Conn_dropped	string	`json:"CONN_DROPPED"`
	Last_reset	string	`json:"LAST_RESET"`
	Last_reset_reason	string	`json:"LAST_RESET_REASON"`
	Last_peer_reset	string	`json:"LAST_PEER_RESET"`
	Last_peer_reset_reason	string	`json:"LAST_PEER_RESET_REASON"`
	Addr_family	[]string	`json:"ADDR_FAMILY"`
	Table_version	[]string	`json:"TABLE_VERSION"`
	Nei_table_version	[]string	`json:"NEI_TABLE_VERSION"`
	Addr_fam_adv	string	`json:"ADDR_FAM_ADV"`
	Addr_fam_rcv	string	`json:"ADDR_FAM_RCV"`
	Localhost_ip	string	`json:"LOCALHOST_IP"`
	Localhost_port	string	`json:"LOCALHOST_PORT"`
	Remote_ip	string	`json:"REMOTE_IP"`
	Remote_port	string	`json:"REMOTE_PORT"`
	Accepted_paths	string	`json:"ACCEPTED_PATHS"`
	Sent_paths	string	`json:"SENT_PATHS"`
	Consumed_mem	string	`json:"CONSUMED_MEM"`
	Rr_old_cap	string	`json:"RR_OLD_CAP"`
	Rr_new_cap	string	`json:"RR_NEW_CAP"`
	Graceful_cap	string	`json:"GRACEFUL_CAP"`
	Fourbyte_cap	string	`json:"FOURBYTE_CAP"`
	Ext_nh_cap	string	`json:"EXT_NH_CAP"`
	Restart_time_adv	string	`json:"RESTART_TIME_ADV"`
	Restart_time_rcv	string	`json:"RESTART_TIME_RCV"`
	Stale_time	string	`json:"STALE_TIME"`
	Opens_count_sent	string	`json:"OPENS_COUNT_SENT"`
	Notifications_count_sent	string	`json:"NOTIFICATIONS_COUNT_SENT"`
	Updates_count_sent	string	`json:"UPDATES_COUNT_SENT"`
	Keepalives_count_sent	string	`json:"KEEPALIVES_COUNT_SENT"`
	Route_refresh_count_sent	string	`json:"ROUTE_REFRESH_COUNT_SENT"`
	Capability_count_sent	string	`json:"CAPABILITY_COUNT_SENT"`
	Total_mess_count_sent	string	`json:"TOTAL_MESS_COUNT_SENT"`
	Total_bytes_count_sent	string	`json:"TOTAL_BYTES_COUNT_SENT"`
	Opens_count_rcvd	string	`json:"OPENS_COUNT_RCVD"`
	Notifications_count_rcvd	string	`json:"NOTIFICATIONS_COUNT_RCVD"`
	Updates_count_rcvd	string	`json:"UPDATES_COUNT_RCVD"`
	Keepalives_count_rcvd	string	`json:"KEEPALIVES_COUNT_RCVD"`
	Route_refresh_count_rcvd	string	`json:"ROUTE_REFRESH_COUNT_RCVD"`
	Capability_count_rcvd	string	`json:"CAPABILITY_COUNT_RCVD"`
	Total_mess_count_rcvd	string	`json:"TOTAL_MESS_COUNT_RCVD"`
	Total_bytes_count_rcvd	string	`json:"TOTAL_BYTES_COUNT_RCVD"`
	Total_bytes_send_queue	string	`json:"TOTAL_BYTES_SEND_QUEUE"`
	Total_bytes_rcvd_queue	string	`json:"TOTAL_BYTES_RCVD_QUEUE"`
	Inbound_routemap	string	`json:"INBOUND_ROUTEMAP"`
	Outbound_routemap	string	`json:"OUTBOUND_ROUTEMAP"`
}