package models

type CiscoAsaShowAccessList struct {
	Acl_name	string	`json:"ACL_NAME"`
	Acl_tot_elem	string	`json:"ACL_TOT_ELEM"`
	Acl_name_hash	string	`json:"ACL_NAME_HASH"`
	Type	string	`json:"TYPE"`
	Line_num	string	`json:"LINE_NUM"`
	Remark	string	`json:"REMARK"`
	Action	string	`json:"ACTION"`
	Protocol	string	`json:"PROTOCOL"`
	Svc_object_grp	string	`json:"SVC_OBJECT_GRP"`
	Svc_object	string	`json:"SVC_OBJECT"`
	Src_intfc	string	`json:"SRC_INTFC"`
	Src_object_grp	string	`json:"SRC_OBJECT_GRP"`
	Src_object	string	`json:"SRC_OBJECT"`
	Src_host	string	`json:"SRC_HOST"`
	Src_v6host	string	`json:"SRC_V6HOST"`
	Src_network	string	`json:"SRC_NETWORK"`
	Src_v6network	string	`json:"SRC_V6NETWORK"`
	Src_mask	string	`json:"SRC_MASK"`
	Src_v6mask	string	`json:"SRC_V6MASK"`
	Src_any	string	`json:"SRC_ANY"`
	Dst_intfc	string	`json:"DST_INTFC"`
	Dst_object_grp	string	`json:"DST_OBJECT_GRP"`
	Dst_object	string	`json:"DST_OBJECT"`
	Dst_host	string	`json:"DST_HOST"`
	Dst_v6host	string	`json:"DST_V6HOST"`
	Dst_network	string	`json:"DST_NETWORK"`
	Dst_v6network	string	`json:"DST_V6NETWORK"`
	Dst_mask	string	`json:"DST_MASK"`
	Dst_v6mask	string	`json:"DST_V6MASK"`
	Dst_any	string	`json:"DST_ANY"`
	Dst_port	string	`json:"DST_PORT"`
	Dst_port_less_than	string	`json:"DST_PORT_LESS_THAN"`
	Dst_port_greater_than	string	`json:"DST_PORT_GREATER_THAN"`
	Dst_port_range_start	string	`json:"DST_PORT_RANGE_START"`
	Dst_port_range_end	string	`json:"DST_PORT_RANGE_END"`
	Dst_port_grp	string	`json:"DST_PORT_GRP"`
	Dst_port_object	string	`json:"DST_PORT_OBJECT"`
	Dst_icmp_type	string	`json:"DST_ICMP_TYPE"`
	Log_level	string	`json:"LOG_LEVEL"`
	Log_interval	string	`json:"LOG_INTERVAL"`
	Time_range	string	`json:"TIME_RANGE"`
	State	string	`json:"STATE"`
	Hit_count	string	`json:"HIT_COUNT"`
	Line_hash	string	`json:"LINE_HASH"`
	Entry_protocol_icmp	string	`json:"ENTRY_PROTOCOL_ICMP"`
	Entry_protocol	string	`json:"ENTRY_PROTOCOL"`
	Entry_src_fqdn	string	`json:"ENTRY_SRC_FQDN"`
	Entry_src_range_start	string	`json:"ENTRY_SRC_RANGE_START"`
	Entry_src_range_end	string	`json:"ENTRY_SRC_RANGE_END"`
	Entry_src_host	string	`json:"ENTRY_SRC_HOST"`
	Entry_src_v6host	string	`json:"ENTRY_SRC_V6HOST"`
	Entry_src_network	string	`json:"ENTRY_SRC_NETWORK"`
	Entry_src_v6network	string	`json:"ENTRY_SRC_V6NETWORK"`
	Entry_src_mask	string	`json:"ENTRY_SRC_MASK"`
	Entry_src_v6mask	string	`json:"ENTRY_SRC_V6MASK"`
	Entry_src_any	string	`json:"ENTRY_SRC_ANY"`
	Entry_src_fqdn_state	string	`json:"ENTRY_SRC_FQDN_STATE"`
	Entry_dst_fqdn	string	`json:"ENTRY_DST_FQDN"`
	Entry_dst_range_start	string	`json:"ENTRY_DST_RANGE_START"`
	Entry_dst_range_end	string	`json:"ENTRY_DST_RANGE_END"`
	Entry_dst_host	string	`json:"ENTRY_DST_HOST"`
	Entry_dst_v6host	string	`json:"ENTRY_DST_V6HOST"`
	Entry_dst_network	string	`json:"ENTRY_DST_NETWORK"`
	Entry_dst_v6network	string	`json:"ENTRY_DST_V6NETWORK"`
	Entry_dst_mask	string	`json:"ENTRY_DST_MASK"`
	Entry_dst_v6mask	string	`json:"ENTRY_DST_V6MASK"`
	Entry_dst_any	string	`json:"ENTRY_DST_ANY"`
	Entry_dst_fqdn_state	string	`json:"ENTRY_DST_FQDN_STATE"`
	Entry_icmp_type	string	`json:"ENTRY_ICMP_TYPE"`
	Entry_icmp_code	string	`json:"ENTRY_ICMP_CODE"`
	Entry_port	string	`json:"ENTRY_PORT"`
	Entry_port_less_than	string	`json:"ENTRY_PORT_LESS_THAN"`
	Entry_port_greater_than	string	`json:"ENTRY_PORT_GREATER_THAN"`
	Entry_port_range_start	string	`json:"ENTRY_PORT_RANGE_START"`
	Entry_port_range_end	string	`json:"ENTRY_PORT_RANGE_END"`
	Entry_hit_count	string	`json:"ENTRY_HIT_COUNT"`
	Entry_state	string	`json:"ENTRY_STATE"`
	Entry_hash	string	`json:"ENTRY_HASH"`
}