package models

type CiscoAsaShowInterfaceDetail struct {
	Interface	string	`json:"INTERFACE"`
	Interface_name	string	`json:"INTERFACE_NAME"`
	Link_status	string	`json:"LINK_STATUS"`
	Protocol_status	string	`json:"PROTOCOL_STATUS"`
	Hardware_type	string	`json:"HARDWARE_TYPE"`
	Bandwidth	string	`json:"BANDWIDTH"`
	Delay	string	`json:"DELAY"`
	Duplex	string	`json:"DUPLEX"`
	Speed	string	`json:"SPEED"`
	Flowcontrol_in	string	`json:"FLOWCONTROL_IN"`
	Flowcontrol_out	string	`json:"FLOWCONTROL_OUT"`
	Bonded_port	string	`json:"BONDED_PORT"`
	Description	string	`json:"DESCRIPTION"`
	Mac_address	string	`json:"MAC_ADDRESS"`
	Mtu	string	`json:"MTU"`
	Ip_address	string	`json:"IP_ADDRESS"`
	Netmask	string	`json:"NETMASK"`
	In_packets	string	`json:"IN_PACKETS"`
	In_bytes	string	`json:"IN_BYTES"`
	No_buffer	string	`json:"NO_BUFFER"`
	Broadcasts	string	`json:"BROADCASTS"`
	Runts	string	`json:"RUNTS"`
	Giants	string	`json:"GIANTS"`
	In_errors	string	`json:"IN_ERRORS"`
	Crc	string	`json:"CRC"`
	Frame	string	`json:"FRAME"`
	Overrun	string	`json:"OVERRUN"`
	Ignored	string	`json:"IGNORED"`
	Abort	string	`json:"ABORT"`
	In_pause_resume	string	`json:"IN_PAUSE_RESUME"`
	In_pause	string	`json:"IN_PAUSE"`
	In_resume	string	`json:"IN_RESUME"`
	L2_decode_drops	string	`json:"L2_DECODE_DROPS"`
	Switch_ingress_policy_drops	string	`json:"SWITCH_INGRESS_POLICY_DROPS"`
	Out_packets	string	`json:"OUT_PACKETS"`
	Out_bytes	string	`json:"OUT_BYTES"`
	Underruns	string	`json:"UNDERRUNS"`
	Out_pause_resume	string	`json:"OUT_PAUSE_RESUME"`
	Out_pause	string	`json:"OUT_PAUSE"`
	Out_resume	string	`json:"OUT_RESUME"`
	Out_errors	string	`json:"OUT_ERRORS"`
	Collisions	string	`json:"COLLISIONS"`
	Interface_resets	string	`json:"INTERFACE_RESETS"`
	Late_collisions	string	`json:"LATE_COLLISIONS"`
	Deferred	string	`json:"DEFERRED"`
	Out_decode_drops	string	`json:"OUT_DECODE_DROPS"`
	Rate_limit_drops	string	`json:"RATE_LIMIT_DROPS"`
	Switch_egress_policy_drops	string	`json:"SWITCH_EGRESS_POLICY_DROPS"`
	In_reset_drops	string	`json:"IN_RESET_DROPS"`
	Out_reset_drops	string	`json:"OUT_RESET_DROPS"`
	Vlan_id	string	`json:"VLAN_ID"`
	Control_interface_number	string	`json:"CONTROL_INTERFACE_NUMBER"`
	Control_interface_config_status	string	`json:"CONTROL_INTERFACE_CONFIG_STATUS"`
	Control_interface_state	string	`json:"CONTROL_INTERFACE_STATE"`
	Rxring_number	[]string	`json:"RXRING_NUMBER"`
	Rxring_packets	[]string	`json:"RXRING_PACKETS"`
	Rxring_bytes	[]string	`json:"RXRING_BYTES"`
	Rxring_overrun	[]string	`json:"RXRING_OVERRUN"`
	Rxring_blocks_free_curr	[]string	`json:"RXRING_BLOCKS_FREE_CURR"`
	Rxring_blocks_free_low	[]string	`json:"RXRING_BLOCKS_FREE_LOW"`
	Rxring_interface	[]string	`json:"RXRING_INTERFACE"`
	Txring_number	[]string	`json:"TXRING_NUMBER"`
	Txring_packets	[]string	`json:"TXRING_PACKETS"`
	Txring_bytes	[]string	`json:"TXRING_BYTES"`
	Txring_underrun	[]string	`json:"TXRING_UNDERRUN"`
	Txring_blocks_free_curr	[]string	`json:"TXRING_BLOCKS_FREE_CURR"`
	Txring_blocks_free_low	[]string	`json:"TXRING_BLOCKS_FREE_LOW"`
	Txring_interface	[]string	`json:"TXRING_INTERFACE"`
}