package models

type CiscoAsaShowVpnSessiondbDetailL2l struct {
	Session_type	string	`json:"SESSION_TYPE"`
	Connection	string	`json:"CONNECTION"`
	Index	string	`json:"INDEX"`
	Ip_address	string	`json:"IP_ADDRESS"`
	Protocol	string	`json:"PROTOCOL"`
	Encryption	string	`json:"ENCRYPTION"`
	Hashing	string	`json:"HASHING"`
	Total_bytes_transmitted	string	`json:"TOTAL_BYTES_TRANSMITTED"`
	Total_bytes_received	string	`json:"TOTAL_BYTES_RECEIVED"`
	Login_time	string	`json:"LOGIN_TIME"`
	Login_time_zone	string	`json:"LOGIN_TIME_ZONE"`
	Login_weekday	string	`json:"LOGIN_WEEKDAY"`
	Login_month	string	`json:"LOGIN_MONTH"`
	Login_day	string	`json:"LOGIN_DAY"`
	Login_year	string	`json:"LOGIN_YEAR"`
	Duration	string	`json:"DURATION"`
	Filter_name	string	`json:"FILTER_NAME"`
	Total_ike_sessions	string	`json:"TOTAL_IKE_SESSIONS"`
	Total_ipsec_sessions	string	`json:"TOTAL_IPSEC_SESSIONS"`
	Connection_type	string	`json:"CONNECTION_TYPE"`
	Session_id	string	`json:"SESSION_ID"`
	Udp_src_port	string	`json:"UDP_SRC_PORT"`
	Udp_dst_port	string	`json:"UDP_DST_PORT"`
	Negotiaion_mode	string	`json:"NEGOTIAION_MODE"`
	Authentication_mode	string	`json:"AUTHENTICATION_MODE"`
	Remote_authentication_mode	string	`json:"REMOTE_AUTHENTICATION_MODE"`
	Local_authentication_mode	string	`json:"LOCAL_AUTHENTICATION_MODE"`
	Encryption_method	string	`json:"ENCRYPTION_METHOD"`
	Hash_method	string	`json:"HASH_METHOD"`
	Rekey_interval	string	`json:"REKEY_INTERVAL"`
	Rekey_interval_unit	string	`json:"REKEY_INTERVAL_UNIT"`
	Rekey_time_left	string	`json:"REKEY_TIME_LEFT"`
	Rekey_time_left_unit	string	`json:"REKEY_TIME_LEFT_UNIT"`
	Rekey_data_interval	string	`json:"REKEY_DATA_INTERVAL"`
	Rekey_data_interval_unit	string	`json:"REKEY_DATA_INTERVAL_UNIT"`
	Rekey_data_remaining	string	`json:"REKEY_DATA_REMAINING"`
	Rekey_data_remaining_unit	string	`json:"REKEY_DATA_REMAINING_UNIT"`
	Idle_timeout_interval	string	`json:"IDLE_TIMEOUT_INTERVAL"`
	Idle_timeout_interval_unit	string	`json:"IDLE_TIMEOUT_INTERVAL_UNIT"`
	Idle_timeout_remaining	string	`json:"IDLE_TIMEOUT_REMAINING"`
	Idle_timeout_remaining_unit	string	`json:"IDLE_TIMEOUT_REMAINING_UNIT"`
	Prf	string	`json:"PRF"`
	Dh_group	string	`json:"DH_GROUP"`
	Ipv6_filter_name	string	`json:"IPV6_FILTER_NAME"`
	Local_address_network	string	`json:"LOCAL_ADDRESS_NETWORK"`
	Local_address_mask	string	`json:"LOCAL_ADDRESS_MASK"`
	Remote_address_network	string	`json:"REMOTE_ADDRESS_NETWORK"`
	Remote_address_mask	string	`json:"REMOTE_ADDRESS_MASK"`
	Encapsulation	string	`json:"ENCAPSULATION"`
	Pfs_group	string	`json:"PFS_GROUP"`
	Bytes_transmitted	string	`json:"BYTES_TRANSMITTED"`
	Bytes_received	string	`json:"BYTES_RECEIVED"`
	Packets_transmitted	string	`json:"PACKETS_TRANSMITTED"`
	Packets_received	string	`json:"PACKETS_RECEIVED"`
	Reval_timeout	string	`json:"REVAL_TIMEOUT"`
	Reval_timout_unit	string	`json:"REVAL_TIMOUT_UNIT"`
	Reval_timeout_remaining	string	`json:"REVAL_TIMEOUT_REMAINING"`
	Reval_timeout_remaining_unit	string	`json:"REVAL_TIMEOUT_REMAINING_UNIT"`
	Status_query_interval	string	`json:"STATUS_QUERY_INTERVAL"`
	Status_query_interval_unit	string	`json:"STATUS_QUERY_INTERVAL_UNIT"`
	Eap_over_udp_timer	string	`json:"EAP_OVER_UDP_TIMER"`
	Eap_over_udp_timer_unit	string	`json:"EAP_OVER_UDP_TIMER_UNIT"`
	Posture_holdtime_remaining	string	`json:"POSTURE_HOLDTIME_REMAINING"`
	Posture_holdtime_remaining_unit	string	`json:"POSTURE_HOLDTIME_REMAINING_UNIT"`
	Posture_token	string	`json:"POSTURE_TOKEN"`
	Redirect_url	string	`json:"REDIRECT_URL"`
}