package models

type CiscoAsaShowCryptoIpsecSa struct {
	Interface	string	`json:"INTERFACE"`
	Crypto_map_tag	string	`json:"CRYPTO_MAP_TAG"`
	Sequence_number	string	`json:"SEQUENCE_NUMBER"`
	Local_address	string	`json:"LOCAL_ADDRESS"`
	Local_address_name	string	`json:"LOCAL_ADDRESS_NAME"`
	Local_identity_addr	string	`json:"LOCAL_IDENTITY_ADDR"`
	Local_identity_mask	string	`json:"LOCAL_IDENTITY_MASK"`
	Local_identity_protocol	string	`json:"LOCAL_IDENTITY_PROTOCOL"`
	Local_identity_port	string	`json:"LOCAL_IDENTITY_PORT"`
	Remote_identity_addr	string	`json:"REMOTE_IDENTITY_ADDR"`
	Remote_identity_mask	string	`json:"REMOTE_IDENTITY_MASK"`
	Remote_identity_protocol	string	`json:"REMOTE_IDENTITY_PROTOCOL"`
	Remote_identity_port	string	`json:"REMOTE_IDENTITY_PORT"`
	Current_peer	string	`json:"CURRENT_PEER"`
	Dynamic_peer	string	`json:"DYNAMIC_PEER"`
	Current_peer_name	string	`json:"CURRENT_PEER_NAME"`
	Dynamic_peer_name	string	`json:"DYNAMIC_PEER_NAME"`
	Packets_encapsulated	string	`json:"PACKETS_ENCAPSULATED"`
	Packets_encrypted	string	`json:"PACKETS_ENCRYPTED"`
	Packets_digested	string	`json:"PACKETS_DIGESTED"`
	Packets_decapsulated	string	`json:"PACKETS_DECAPSULATED"`
	Packets_decrypted	string	`json:"PACKETS_DECRYPTED"`
	Packets_verified	string	`json:"PACKETS_VERIFIED"`
	Packets_compressed	string	`json:"PACKETS_COMPRESSED"`
	Packets_decompressed	string	`json:"PACKETS_DECOMPRESSED"`
	Packets_not_compressed	string	`json:"PACKETS_NOT_COMPRESSED"`
	Packets_compress_failed	string	`json:"PACKETS_COMPRESS_FAILED"`
	Packets_decompress_failed	string	`json:"PACKETS_DECOMPRESS_FAILED"`
	Pre_fragment_success	string	`json:"PRE_FRAGMENT_SUCCESS"`
	Pre_fragment_failures	string	`json:"PRE_FRAGMENT_FAILURES"`
	Fragments_created	string	`json:"FRAGMENTS_CREATED"`
	Pmtus_sent	string	`json:"PMTUS_SENT"`
	Pmtus_received	string	`json:"PMTUS_RECEIVED"`
	Decap_frags_needing_reassembly	string	`json:"DECAP_FRAGS_NEEDING_REASSEMBLY"`
	Send_errors	string	`json:"SEND_ERRORS"`
	Receive_errors	string	`json:"RECEIVE_ERRORS"`
	Local_crypto_endpoint	string	`json:"LOCAL_CRYPTO_ENDPOINT"`
	Remote_crypto_endpoint	string	`json:"REMOTE_CRYPTO_ENDPOINT"`
	Local_crypto_endpoint_name	string	`json:"LOCAL_CRYPTO_ENDPOINT_NAME"`
	Remote_crypto_endpoint_name	string	`json:"REMOTE_CRYPTO_ENDPOINT_NAME"`
	Path_mtu	string	`json:"PATH_MTU"`
	Ipsec_overhead	string	`json:"IPSEC_OVERHEAD"`
	Media_mtu	string	`json:"MEDIA_MTU"`
	Current_inbound_spi	string	`json:"CURRENT_INBOUND_SPI"`
	Current_outbound_spi	string	`json:"CURRENT_OUTBOUND_SPI"`
	Inbound_spi_hex	string	`json:"INBOUND_SPI_HEX"`
	Inbound_spi_integer	string	`json:"INBOUND_SPI_INTEGER"`
	Inbound_encryption	string	`json:"INBOUND_ENCRYPTION"`
	Inbound_authentication	string	`json:"INBOUND_AUTHENTICATION"`
	Inbound_settings_in_use	string	`json:"INBOUND_SETTINGS_IN_USE"`
	Inbound_slot	string	`json:"INBOUND_SLOT"`
	Inbound_connection_id	string	`json:"INBOUND_CONNECTION_ID"`
	Inbound_crypto_map	string	`json:"INBOUND_CRYPTO_MAP"`
	Inbound_remaining_lifetime	string	`json:"INBOUND_REMAINING_LIFETIME"`
	Inbound_remaining_lifetime_kilobytes	string	`json:"INBOUND_REMAINING_LIFETIME_KILOBYTES"`
	Inbound_iv_size	string	`json:"INBOUND_IV_SIZE"`
	Inbound_replay_detection	string	`json:"INBOUND_REPLAY_DETECTION"`
	Outbound_spi_hex	string	`json:"OUTBOUND_SPI_HEX"`
	Outbound_spi_integer	string	`json:"OUTBOUND_SPI_INTEGER"`
	Outbound_encryption	string	`json:"OUTBOUND_ENCRYPTION"`
	Outbound_authentication	string	`json:"OUTBOUND_AUTHENTICATION"`
	Outbound_settings_in_use	string	`json:"OUTBOUND_SETTINGS_IN_USE"`
	Outbound_slot	string	`json:"OUTBOUND_SLOT"`
	Outbound_connection_id	string	`json:"OUTBOUND_CONNECTION_ID"`
	Outbound_crypto_map	string	`json:"OUTBOUND_CRYPTO_MAP"`
	Outbound_remaining_lifetime	string	`json:"OUTBOUND_REMAINING_LIFETIME"`
	Outbound_remaining_lifetime_kilobytes	string	`json:"OUTBOUND_REMAINING_LIFETIME_KILOBYTES"`
	Outbound_iv_size	string	`json:"OUTBOUND_IV_SIZE"`
	Outbound_replay_detection	string	`json:"OUTBOUND_REPLAY_DETECTION"`
}