package models

type CiscoWlcSshShow80211aCleanairConfig struct {
	Cleanair	string	`json:"CLEANAIR"`
	Air_quality_report	string	`json:"AIR_QUALITY_REPORT"`
	Air_quality_period	string	`json:"AIR_QUALITY_PERIOD"`
	Air_quality_alarm	string	`json:"AIR_QUALITY_ALARM"`
	Aq_alarm_thresh	string	`json:"AQ_ALARM_THRESH"`
	Aq_unclassified_inter	string	`json:"AQ_UNCLASSIFIED_INTER"`
	Aq_unclassified_thresh	string	`json:"AQ_UNCLASSIFIED_THRESH"`
	Interfere_device_report	string	`json:"INTERFERE_DEVICE_REPORT"`
	Bluetooth_link	string	`json:"BLUETOOTH_LINK"`
	Microwave	string	`json:"MICROWAVE"`
	Dot11_fh	string	`json:"DOT11_FH"`
	Bluetooth_discovery	string	`json:"BLUETOOTH_DISCOVERY"`
	Tdd_transmit	string	`json:"TDD_TRANSMIT"`
	Jammer	string	`json:"JAMMER"`
	Continuous_transmit	string	`json:"CONTINUOUS_TRANSMIT"`
	Dect_like_phone	string	`json:"DECT_LIKE_PHONE"`
	Video_camera	string	`json:"VIDEO_CAMERA"`
	Dot15_4	string	`json:"DOT15_4"`
	Wifi_inverted	string	`json:"WIFI_INVERTED"`
	Wifi_invalid_channel	string	`json:"WIFI_INVALID_CHANNEL"`
	Superag	string	`json:"SUPERAG"`
	Canopy	string	`json:"CANOPY"`
	Microsoft_device	string	`json:"MICROSOFT_DEVICE"`
	Wimax_mobile	string	`json:"WIMAX_MOBILE"`
	Wimax_fixed	string	`json:"WIMAX_FIXED"`
	Ble_beacon	string	`json:"BLE_BEACON"`
	Int_device_alarm	string	`json:"INT_DEVICE_ALARM"`
	Bluetooth_link_alarm	string	`json:"BLUETOOTH_LINK_ALARM"`
	Microwave_alarm	string	`json:"MICROWAVE_ALARM"`
	Dot11_fh_alarm	string	`json:"DOT11_FH_ALARM"`
	Bluetooth_discovery_alarm	string	`json:"BLUETOOTH_DISCOVERY_ALARM"`
	Tdd_transmit_alarm	string	`json:"TDD_TRANSMIT_ALARM"`
	Jammer_alarm	string	`json:"JAMMER_ALARM"`
	Continuous_transmit_alarm	string	`json:"CONTINUOUS_TRANSMIT_ALARM"`
	Dect_like_phone_alarm	string	`json:"DECT_LIKE_PHONE_ALARM"`
	Video_camera_alarm	string	`json:"VIDEO_CAMERA_ALARM"`
	Dot15_4_alarm	string	`json:"DOT15_4_ALARM"`
	Wifi_inverted_alarm	string	`json:"WIFI_INVERTED_ALARM"`
	Wifi_invalid_channel_alarm	string	`json:"WIFI_INVALID_CHANNEL_ALARM"`
	Superag_alarm	string	`json:"SUPERAG_ALARM"`
	Canopy_alarm	string	`json:"CANOPY_ALARM"`
	Microsoft_device_alarm	string	`json:"MICROSOFT_DEVICE_ALARM"`
	Wimax_mobile_alarm	string	`json:"WIMAX_MOBILE_ALARM"`
	Wimax_fixed_alarm	string	`json:"WIMAX_FIXED_ALARM"`
	Ble_beacon_alarm	string	`json:"BLE_BEACON_ALARM"`
	Ed_rrm_state	string	`json:"ED_RRM_STATE"`
	Ed_rrm_sensitivity	string	`json:"ED_RRM_SENSITIVITY"`
	Ed_rrm_thresh	string	`json:"ED_RRM_THRESH"`
	Rogue_contribution	string	`json:"ROGUE_CONTRIBUTION"`
	Rogue_duty_cycle_thresh	string	`json:"ROGUE_DUTY_CYCLE_THRESH"`
	Persistant_device_state	string	`json:"PERSISTANT_DEVICE_STATE"`
	Persistant_device_propagation	string	`json:"PERSISTANT_DEVICE_PROPAGATION"`
}