package models

type CiscoNxosShowIpInterface struct {
	Vrf_name	string	`json:"VRF_NAME"`
	Interface	string	`json:"INTERFACE"`
	Protocol_status	string	`json:"PROTOCOL_STATUS"`
	Link_status	string	`json:"LINK_STATUS"`
	Admin_status	string	`json:"ADMIN_STATUS"`
	Primary_ip_address	string	`json:"PRIMARY_IP_ADDRESS"`
	Primary_ip_subnet	string	`json:"PRIMARY_IP_SUBNET"`
	Primary_broadcast_address	string	`json:"PRIMARY_BROADCAST_ADDRESS"`
	Secondary_ip_address	[]string	`json:"SECONDARY_IP_ADDRESS"`
	Secondary_ip_subnet	[]string	`json:"SECONDARY_IP_SUBNET"`
	Secondary_route_preference	[]string	`json:"SECONDARY_ROUTE_PREFERENCE"`
	Secondary_route_preference_tag	[]string	`json:"SECONDARY_ROUTE_PREFERENCE_TAG"`
	Multicast_groups	string	`json:"MULTICAST_GROUPS"`
	Mtu	string	`json:"MTU"`
	Route_preference	string	`json:"ROUTE_PREFERENCE"`
	Route_preference_tag	string	`json:"ROUTE_PREFERENCE_TAG"`
	Proxy_arp	string	`json:"PROXY_ARP"`
	Local_proxy_arp	string	`json:"LOCAL_PROXY_ARP"`
	Multicast_routing	string	`json:"MULTICAST_ROUTING"`
	Icmp_redirects	string	`json:"ICMP_REDIRECTS"`
	Directed_broadcast	string	`json:"DIRECTED_BROADCAST"`
	Ip_forwarding	string	`json:"IP_FORWARDING"`
	Icmp_unreachables	string	`json:"ICMP_UNREACHABLES"`
	Icmp_port_unreachable	string	`json:"ICMP_PORT_UNREACHABLE"`
	Urpf	string	`json:"URPF"`
	Load_sharing	string	`json:"LOAD_SHARING"`
	Last_reset	string	`json:"LAST_RESET"`
	Acl_out	string	`json:"ACL_OUT"`
	Unicast_packets_sent	string	`json:"UNICAST_PACKETS_SENT"`
	Unicast_packets_received	string	`json:"UNICAST_PACKETS_RECEIVED"`
	Unicast_packets_forwarded	string	`json:"UNICAST_PACKETS_FORWARDED"`
	Unicast_packets_originated	string	`json:"UNICAST_PACKETS_ORIGINATED"`
	Unicast_packets_consumed	string	`json:"UNICAST_PACKETS_CONSUMED"`
	Unicast_bytes_sent	string	`json:"UNICAST_BYTES_SENT"`
	Unicast_bytes_received	string	`json:"UNICAST_BYTES_RECEIVED"`
	Unicast_bytes_forwarded	string	`json:"UNICAST_BYTES_FORWARDED"`
	Unicast_bytes_originated	string	`json:"UNICAST_BYTES_ORIGINATED"`
	Unicast_bytes_consumed	string	`json:"UNICAST_BYTES_CONSUMED"`
	Multicast_packets_sent	string	`json:"MULTICAST_PACKETS_SENT"`
	Multicast_packets_received	string	`json:"MULTICAST_PACKETS_RECEIVED"`
	Multicast_packets_forwarded	string	`json:"MULTICAST_PACKETS_FORWARDED"`
	Multicast_packets_originated	string	`json:"MULTICAST_PACKETS_ORIGINATED"`
	Multicast_packets_consumed	string	`json:"MULTICAST_PACKETS_CONSUMED"`
	Multicast_bytes_sent	string	`json:"MULTICAST_BYTES_SENT"`
	Multicast_bytes_received	string	`json:"MULTICAST_BYTES_RECEIVED"`
	Multicast_bytes_forwarded	string	`json:"MULTICAST_BYTES_FORWARDED"`
	Multicast_bytes_originated	string	`json:"MULTICAST_BYTES_ORIGINATED"`
	Multicast_bytes_consumed	string	`json:"MULTICAST_BYTES_CONSUMED"`
	Broadcast_packets_sent	string	`json:"BROADCAST_PACKETS_SENT"`
	Broadcast_packets_received	string	`json:"BROADCAST_PACKETS_RECEIVED"`
	Broadcast_packets_forwarded	string	`json:"BROADCAST_PACKETS_FORWARDED"`
	Broadcast_packets_originated	string	`json:"BROADCAST_PACKETS_ORIGINATED"`
	Broadcast_packets_consumed	string	`json:"BROADCAST_PACKETS_CONSUMED"`
	Broadcast_bytes_sent	string	`json:"BROADCAST_BYTES_SENT"`
	Broadcast_bytes_received	string	`json:"BROADCAST_BYTES_RECEIVED"`
	Broadcast_bytes_forwarded	string	`json:"BROADCAST_BYTES_FORWARDED"`
	Broadcast_bytes_originated	string	`json:"BROADCAST_BYTES_ORIGINATED"`
	Broadcast_bytes_consumed	string	`json:"BROADCAST_BYTES_CONSUMED"`
	Labeled_packets_sent	string	`json:"LABELED_PACKETS_SENT"`
	Labeled_packets_received	string	`json:"LABELED_PACKETS_RECEIVED"`
	Labeled_packets_forwarded	string	`json:"LABELED_PACKETS_FORWARDED"`
	Labeled_packets_originated	string	`json:"LABELED_PACKETS_ORIGINATED"`
	Labeled_packets_consumed	string	`json:"LABELED_PACKETS_CONSUMED"`
	Labeled_bytes_sent	string	`json:"LABELED_BYTES_SENT"`
	Labeled_bytes_received	string	`json:"LABELED_BYTES_RECEIVED"`
	Labeled_bytes_forwarded	string	`json:"LABELED_BYTES_FORWARDED"`
	Labeled_bytes_originated	string	`json:"LABELED_BYTES_ORIGINATED"`
	Labeled_bytes_consumed	string	`json:"LABELED_BYTES_CONSUMED"`
	Wccp_redirect_outbound	string	`json:"WCCP_REDIRECT_OUTBOUND"`
	Wccp_redirect_inbound	string	`json:"WCCP_REDIRECT_INBOUND"`
	Wccp_redirect_exclude	string	`json:"WCCP_REDIRECT_EXCLUDE"`
}