package models

type CiscoNxosShowHardwareInternalBigsurAllPortsDetail struct {
	Port_name	string	`json:"PORT_NAME"`
	Interface_index	string	`json:"INTERFACE_INDEX"`
	Instance_index	string	`json:"INSTANCE_INDEX"`
	Instance_slot	string	`json:"INSTANCE_SLOT"`
	Instance_asic	string	`json:"INSTANCE_ASIC"`
	Asic_eport	string	`json:"ASIC_EPORT"`
	Logical_port	string	`json:"LOGICAL_PORT"`
	Front_port	string	`json:"FRONT_PORT"`
	State	string	`json:"STATE"`
	Bigsur_eport	string	`json:"BIGSUR_EPORT"`
	Port	string	`json:"PORT"`
	Port_dec	string	`json:"PORT_DEC"`
	Type	string	`json:"TYPE"`
	Firewall_instance	string	`json:"FIREWALL_INSTANCE"`
	Speed	string	`json:"SPEED"`
	Admin_state	string	`json:"ADMIN_STATE"`
	Admin_state_dec	string	`json:"ADMIN_STATE_DEC"`
	Mtu	string	`json:"MTU"`
	Duplexity	string	`json:"DUPLEXITY"`
	Duplexity_dec	string	`json:"DUPLEXITY_DEC"`
	Auto_neg_state	string	`json:"AUTO_NEG_STATE"`
	Auto_neg_state_dec	string	`json:"AUTO_NEG_STATE_DEC"`
	Fast_1g_an_timer	string	`json:"FAST_1G_AN_TIMER"`
	Port_speed	string	`json:"PORT_SPEED"`
	Debounce_time	string	`json:"DEBOUNCE_TIME"`
	Linkup_debounce_time	string	`json:"LINKUP_DEBOUNCE_TIME"`
	Sat_fabric_mode	string	`json:"SAT_FABRIC_MODE"`
	Sat_fabric_mode_hex	string	`json:"SAT_FABRIC_MODE_HEX"`
	Port_flow_ctrl	string	`json:"PORT_FLOW_CTRL"`
	Class_flow_ctrl7_0	string	`json:"CLASS_FLOW_CTRL7_0"`
	Class_flow_ctrl_msk_rx	string	`json:"CLASS_FLOW_CTRL_MSK_RX"`
	Class_flow_ctrl_msk_tx	string	`json:"CLASS_FLOW_CTRL_MSK_TX"`
	Link_state	string	`json:"LINK_STATE"`
	Link_state_dec	string	`json:"LINK_STATE_DEC"`
	Oper_speed	string	`json:"OPER_SPEED"`
	Oper_duplexity	string	`json:"OPER_DUPLEXITY"`
	Oper_duplexity_dec	string	`json:"OPER_DUPLEXITY_DEC"`
	Oper_port_flow_ctrl	string	`json:"OPER_PORT_FLOW_CTRL"`
	Up_count	string	`json:"UP_COUNT"`
	Down_count	string	`json:"DOWN_COUNT"`
	Slot	string	`json:"SLOT"`
	Mm_inst	string	`json:"MM_INST"`
	Mm_mode	string	`json:"MM_MODE"`
	Diag_sts	string	`json:"DIAG_STS"`
	Mac_status_polling	string	`json:"MAC_STATUS_POLLING"`
	An_state	string	`json:"AN_STATE"`
	An_state_dec	string	`json:"AN_STATE_DEC"`
	An_timer	string	`json:"AN_TIMER"`
	Link_fail_inhibit_timer	string	`json:"LINK_FAIL_INHIBIT_TIMER"`
	An_disabled	string	`json:"AN_DISABLED"`
	Mm_port_state	string	`json:"MM_PORT_STATE"`
	Mm_port_state_dec	string	`json:"MM_PORT_STATE_DEC"`
	Mm_port_timer	string	`json:"MM_PORT_TIMER"`
	Remote_fault_disable	string	`json:"REMOTE_FAULT_DISABLE"`
	Adaptive_tuning_disable	string	`json:"ADAPTIVE_TUNING_DISABLE"`
	Link_recovery_disable	string	`json:"LINK_RECOVERY_DISABLE"`
	Link_bring_down_disable	string	`json:"LINK_BRING_DOWN_DISABLE"`
	Dfe_tuning_disable	string	`json:"DFE_TUNING_DISABLE"`
	Force_qsfp_removal	string	`json:"FORCE_QSFP_REMOVAL"`
	Force_qsfp_insertion	string	`json:"FORCE_QSFP_INSERTION"`
	Force_qsfp_fiber_type	string	`json:"FORCE_QSFP_FIBER_TYPE"`
	Force_qsfp_copper_type	string	`json:"FORCE_QSFP_COPPER_TYPE"`
	Serdes_lanes	string	`json:"SERDES_LANES"`
	Dfe_tune_lane_0_dfe_a	string	`json:"DFE_TUNE_LANE_0_DFE_A"`
	Dfe_tune_lane_0_dfe_b	string	`json:"DFE_TUNE_LANE_0_DFE_B"`
	Dfe_tune_lane_0_dfe_tune	string	`json:"DFE_TUNE_LANE_0_DFE_TUNE"`
	Dfe_tune_lane_1_dfe_a	string	`json:"DFE_TUNE_LANE_1_DFE_A"`
	Dfe_tune_lane_1_dfe_b	string	`json:"DFE_TUNE_LANE_1_DFE_B"`
	Dfe_tune_lane_1_dfe_tune	string	`json:"DFE_TUNE_LANE_1_DFE_TUNE"`
	Dfe_tune_lane_2_dfe_a	string	`json:"DFE_TUNE_LANE_2_DFE_A"`
	Dfe_tune_lane_2_dfe_b	string	`json:"DFE_TUNE_LANE_2_DFE_B"`
	Dfe_tune_lane_2_dfe_tune	string	`json:"DFE_TUNE_LANE_2_DFE_TUNE"`
	Dfe_tune_lane_3_dfe_a	string	`json:"DFE_TUNE_LANE_3_DFE_A"`
	Dfe_tune_lane_3_dfe_b	string	`json:"DFE_TUNE_LANE_3_DFE_B"`
	Dfe_tune_lane_3_dfe_tune	string	`json:"DFE_TUNE_LANE_3_DFE_TUNE"`
	Fi_block_lock_0h	string	`json:"FI_BLOCK_LOCK_0H"`
	Fi_block_lock_1h	string	`json:"FI_BLOCK_LOCK_1H"`
	Fi_block_lock_2h	string	`json:"FI_BLOCK_LOCK_2H"`
	Fi_block_lock_3h	string	`json:"FI_BLOCK_LOCK_3H"`
	Tx_pkt_size_lt_64	string	`json:"TX_PKT_SIZE_LT_64"`
	Tx_pkt_size_is_64	string	`json:"TX_PKT_SIZE_IS_64"`
	Tx_pkt_size_is_65_to_127	string	`json:"TX_PKT_SIZE_IS_65_TO_127"`
	Tx_pkt_size_is_128_to_255	string	`json:"TX_PKT_SIZE_IS_128_TO_255"`
	Tx_pkt_size_is_256_to_511	string	`json:"TX_PKT_SIZE_IS_256_TO_511"`
	Tx_pkt_size_is_512_to_1023	string	`json:"TX_PKT_SIZE_IS_512_TO_1023"`
	Tx_pkt_size_is_1024_to_1518	string	`json:"TX_PKT_SIZE_IS_1024_TO_1518"`
	Tx_pkt_size_is_1519_to_2047	string	`json:"TX_PKT_SIZE_IS_1519_TO_2047"`
	Tx_pkt_size_is_2048_to_4095	string	`json:"TX_PKT_SIZE_IS_2048_TO_4095"`
	Tx_pkt_size_is_4095_to_8191	string	`json:"TX_PKT_SIZE_IS_4095_TO_8191"`
	Tx_pkt_size_is_8192_to_9216	string	`json:"TX_PKT_SIZE_IS_8192_TO_9216"`
	Tx_pkt_size_gt_9216	string	`json:"TX_PKT_SIZE_GT_9216"`
	Tx_pkt_total	string	`json:"TX_PKT_TOTAL"`
	Tx_pkt_octets	string	`json:"TX_PKT_OCTETS"`
	Tx_pkt_good	string	`json:"TX_PKT_GOOD"`
	Tx_pkt_ucast	string	`json:"TX_PKT_UCAST"`
	Tx_pkt_mcast	string	`json:"TX_PKT_MCAST"`
	Tx_pkt_bcast	string	`json:"TX_PKT_BCAST"`
	Tx_pkt_vlan	string	`json:"TX_PKT_VLAN"`
	Tx_pkt_802_3x_pause	string	`json:"TX_PKT_802_3X_PAUSE"`
	Tx_pkt_per_priority_pause	string	`json:"TX_PKT_PER_PRIORITY_PAUSE"`
	Tx_pkt_frame_error	string	`json:"TX_PKT_FRAME_ERROR"`
	Rx_pkt_size_lt_64	string	`json:"RX_PKT_SIZE_LT_64"`
	Rx_pkt_size_is_64	string	`json:"RX_PKT_SIZE_IS_64"`
	Rx_pkt_size_is_65_to_127	string	`json:"RX_PKT_SIZE_IS_65_TO_127"`
	Rx_pkt_size_is_128_to_255	string	`json:"RX_PKT_SIZE_IS_128_TO_255"`
	Rx_pkt_size_is_256_to_511	string	`json:"RX_PKT_SIZE_IS_256_TO_511"`
	Rx_pkt_size_is_512_to_1023	string	`json:"RX_PKT_SIZE_IS_512_TO_1023"`
	Rx_pkt_size_is_1024_to_1518	string	`json:"RX_PKT_SIZE_IS_1024_TO_1518"`
	Rx_pkt_size_is_1519_to_2047	string	`json:"RX_PKT_SIZE_IS_1519_TO_2047"`
	Rx_pkt_size_is_2048_to_4095	string	`json:"RX_PKT_SIZE_IS_2048_TO_4095"`
	Rx_pkt_size_is_4095_to_8191	string	`json:"RX_PKT_SIZE_IS_4095_TO_8191"`
	Rx_pkt_size_is_8192_to_9216	string	`json:"RX_PKT_SIZE_IS_8192_TO_9216"`
	Rx_pkt_size_gt_9216	string	`json:"RX_PKT_SIZE_GT_9216"`
	Rx_pkt_total	string	`json:"RX_PKT_TOTAL"`
	Rx_pkt_octets	string	`json:"RX_PKT_OCTETS"`
	Rx_pkt_good	string	`json:"RX_PKT_GOOD"`
	Rx_pkt_ucast	string	`json:"RX_PKT_UCAST"`
	Rx_pkt_mcast	string	`json:"RX_PKT_MCAST"`
	Rx_pkt_bcast	string	`json:"RX_PKT_BCAST"`
	Rx_pkt_vlan	string	`json:"RX_PKT_VLAN"`
	Rx_pkt_oversize	string	`json:"RX_PKT_OVERSIZE"`
	Rx_pkt_toolong	string	`json:"RX_PKT_TOOLONG"`
	Rx_pkt_discard	string	`json:"RX_PKT_DISCARD"`
	Rx_pkt_undersize	string	`json:"RX_PKT_UNDERSIZE"`
	Rx_pkt_fragment	string	`json:"RX_PKT_FRAGMENT"`
	Rx_pkt_crc_not_stomped	string	`json:"RX_PKT_CRC_NOT_STOMPED"`
	Rx_pkt_crc_stomped	string	`json:"RX_PKT_CRC_STOMPED"`
	Rx_pkt_in_range_err	string	`json:"RX_PKT_IN_RANGE_ERR"`
	Rx_pkt_jabber	string	`json:"RX_PKT_JABBER"`
	Rx_pkt_802_3x_pause	string	`json:"RX_PKT_802_3X_PAUSE"`
	Rx_pkt_per_priority_pause	string	`json:"RX_PKT_PER_PRIORITY_PAUSE"`
	Tx_pkt_good_octets	string	`json:"TX_PKT_GOOD_OCTETS"`
	Rx_pkt_good_octets	string	`json:"RX_PKT_GOOD_OCTETS"`
	Sfp_ctrl_bigsur	string	`json:"SFP_CTRL_BIGSUR"`
	Sfp_ctrl_port	string	`json:"SFP_CTRL_PORT"`
	Phy_bigsur	string	`json:"PHY_BIGSUR"`
	Phy_mdio_addr	string	`json:"PHY_MDIO_ADDR"`
	Phy_mdio_master	string	`json:"PHY_MDIO_MASTER"`
	Phy_reset_bigsur	string	`json:"PHY_RESET_BIGSUR"`
	Phy_reset_spio	string	`json:"PHY_RESET_SPIO"`
	Phy_prom_shared	string	`json:"PHY_PROM_SHARED"`
	Serdes_txdata_0	string	`json:"SERDES_TXDATA_0"`
	Serdes_txdata_1	string	`json:"SERDES_TXDATA_1"`
	Serdes_txdata_2	string	`json:"SERDES_TXDATA_2"`
	Serdes_txdata_3	string	`json:"SERDES_TXDATA_3"`
	Phy_pmd_tx_0	string	`json:"PHY_PMD_TX_0"`
	Phy_pmd_tx_1	string	`json:"PHY_PMD_TX_1"`
	Phy_pmd_tx_2	string	`json:"PHY_PMD_TX_2"`
	Pma_pmd_devaddr	string	`json:"PMA_PMD_DEVADDR"`
	Pcs_devaddr	string	`json:"PCS_DEVADDR"`
	Phyxs_devaddr	string	`json:"PHYXS_DEVADDR"`
	Xcvr_devaddr	string	`json:"XCVR_DEVADDR"`
	Phy_present	string	`json:"PHY_PRESENT"`
	Phy_type	string	`json:"PHY_TYPE"`
	Sfp_acc_type	string	`json:"SFP_ACC_TYPE"`
	Dfe_timer	string	`json:"DFE_TIMER"`
	Dfe_timer_running	string	`json:"DFE_TIMER_RUNNING"`
	Init_wait_count	string	`json:"INIT_WAIT_COUNT"`
	Do_tx_disable_clr	string	`json:"DO_TX_DISABLE_CLR"`
	Tx_disable_clr_cnt	string	`json:"TX_DISABLE_CLR_CNT"`
	Qsa_status	string	`json:"QSA_STATUS"`
	Connector_type	string	`json:"CONNECTOR_TYPE"`
	Usb_bus_num	string	`json:"USB_BUS_NUM"`
	Usb_dev_num	string	`json:"USB_DEV_NUM"`
	Usb_priv	string	`json:"USB_PRIV"`
	Reset_done	string	`json:"RESET_DONE"`
	Xcvr_flag_present	string	`json:"XCVR_FLAG_PRESENT"`
	Xcvr_flag_xcvr_not_sfp	string	`json:"XCVR_FLAG_XCVR_NOT_SFP"`
	Xcvr_flag_10g_capable	string	`json:"XCVR_FLAG_10G_CAPABLE"`
	Xcvr_flag_cksum_ok	string	`json:"XCVR_FLAG_CKSUM_OK"`
	Xcvr_flag_security_crc_ok	string	`json:"XCVR_FLAG_SECURITY_CRC_OK"`
	Xcvr_flag_cisco_chk_ok	string	`json:"XCVR_FLAG_CISCO_CHK_OK"`
	Xcvr_flag_ddm_capable	string	`json:"XCVR_FLAG_DDM_CAPABLE"`
	Xcvr_flag_pma_pmd_present	string	`json:"XCVR_FLAG_PMA_PMD_PRESENT"`
	Xcvr_flag_pcs_present	string	`json:"XCVR_FLAG_PCS_PRESENT"`
	Xcvr_flag_phyxs_present	string	`json:"XCVR_FLAG_PHYXS_PRESENT"`
	Xcvr_flag_xcvr_operational	string	`json:"XCVR_FLAG_XCVR_OPERATIONAL"`
	Xcvr_flag_pma_pmd_low_pwr_mode	string	`json:"XCVR_FLAG_PMA_PMD_LOW_PWR_MODE"`
	Xcvr_flag_pcs_low_pwr_mode	string	`json:"XCVR_FLAG_PCS_LOW_PWR_MODE"`
	Xcvr_flag_phyxs_low_pwr_mode	string	`json:"XCVR_FLAG_PHYXS_LOW_PWR_MODE"`
	Xcvr_flag_link_up	string	`json:"XCVR_FLAG_LINK_UP"`
	Xcvr_flag_type_fiber	string	`json:"XCVR_FLAG_TYPE_FIBER"`
	Xcvr_flag_sprom_read_ok	string	`json:"XCVR_FLAG_SPROM_READ_OK"`
	Port_state	string	`json:"PORT_STATE"`
	Xcvr_insert_debounce_timer	string	`json:"XCVR_INSERT_DEBOUNCE_TIMER"`
	Xcvr_link_debounce_timer	string	`json:"XCVR_LINK_DEBOUNCE_TIMER"`
	Xcvr_linkup_debounce_timer	string	`json:"XCVR_LINKUP_DEBOUNCE_TIMER"`
	Xcvr_presence_detect_timer	string	`json:"XCVR_PRESENCE_DETECT_TIMER"`
	Tx_enable_signal	string	`json:"TX_ENABLE_SIGNAL"`
	Debounce_timeout	string	`json:"DEBOUNCE_TIMEOUT"`
	Linkup_debounce_timeout	string	`json:"LINKUP_DEBOUNCE_TIMEOUT"`
	Link_up	string	`json:"LINK_UP"`
	Link_dn_debounce_start	string	`json:"LINK_DN_DEBOUNCE_START"`
	Link_debounce_end	string	`json:"LINK_DEBOUNCE_END"`
	Bit_error_rate	string	`json:"BIT_ERROR_RATE"`
	Bit_error_rate_since_linkup	string	`json:"BIT_ERROR_RATE_SINCE_LINKUP"`
	Error_blocks	string	`json:"ERROR_BLOCKS"`
	Error_blocks_since_linkup	string	`json:"ERROR_BLOCKS_SINCE_LINKUP"`
	Link_up_hex	string	`json:"LINK_UP_HEX"`
	Link_up_dec	string	`json:"LINK_UP_DEC"`
	Link_down_hex	string	`json:"LINK_DOWN_HEX"`
	Link_down_dec	string	`json:"LINK_DOWN_DEC"`
	Link_debounced_with_link_up_hex	string	`json:"LINK_DEBOUNCED_WITH_LINK_UP_HEX"`
	Link_debounced_with_link_up_dec	string	`json:"LINK_DEBOUNCED_WITH_LINK_UP_DEC"`
	Link_debounced_with_link_up_since_last_en_hex	string	`json:"LINK_DEBOUNCED_WITH_LINK_UP_SINCE_LAST_EN_HEX"`
	Link_debounced_with_link_up_since_last_en_dec	string	`json:"LINK_DEBOUNCED_WITH_LINK_UP_SINCE_LAST_EN_DEC"`
}