package models

type CiscoAsaShowRunningConfigTunnelGroup struct {
	Name	string	`json:"NAME"`
	Type	string	`json:"TYPE"`
	Dhcp_selection	[]string	`json:"DHCP_SELECTION"`
	Dhcp_server	[]string	`json:"DHCP_SERVER"`
	Authorization	string	`json:"AUTHORIZATION"`
	Authorization_intfc	string	`json:"AUTHORIZATION_INTFC"`
	Authorization_grp	string	`json:"AUTHORIZATION_GRP"`
	Accounting_grp	string	`json:"ACCOUNTING_GRP"`
	Ipv4_pool_intfc	string	`json:"IPV4_POOL_INTFC"`
	Ipv4_pool_name	string	`json:"IPV4_POOL_NAME"`
	Authentication_intfc	string	`json:"AUTHENTICATION_INTFC"`
	Authentication_pri_grp	string	`json:"AUTHENTICATION_PRI_GRP"`
	Authentication_sec_grp	string	`json:"AUTHENTICATION_SEC_GRP"`
	Authentication_svr	string	`json:"AUTHENTICATION_SVR"`
	Authenticated_user	string	`json:"AUTHENTICATED_USER"`
	Group_policy	string	`json:"GROUP_POLICY"`
	Ipv6_pool_intfc	string	`json:"IPV6_POOL_INTFC"`
	Ipv6_pool_name	string	`json:"IPV6_POOL_NAME"`
	Nat_intfc	string	`json:"NAT_INTFC"`
	Scep_enroll	string	`json:"SCEP_ENROLL"`
	Sec_authentication_grp_intfc	string	`json:"SEC_AUTHENTICATION_GRP_INTFC"`
	Sec_authentication_pri_grp	string	`json:"SEC_AUTHENTICATION_PRI_GRP"`
	Sec_authentication_sec_grp	string	`json:"SEC_AUTHENTICATION_SEC_GRP"`
	Sec_authentication_use_pri_user	string	`json:"SEC_AUTHENTICATION_USE_PRI_USER"`
	Sec_cert_codes	string	`json:"SEC_CERT_CODES"`
	Sec_cert_fallback	string	`json:"SEC_CERT_FALLBACK"`
	Pri_cert_codes	string	`json:"PRI_CERT_CODES"`
	Pri_cert_fallback	string	`json:"PRI_CERT_FALLBACK"`
	Strip_grp	string	`json:"STRIP_GRP"`
	Strip_realm	string	`json:"STRIP_REALM"`
	Ikev1_psk	string	`json:"IKEV1_PSK"`
	Chain	string	`json:"CHAIN"`
	Client_os	[]string	`json:"CLIENT_OS"`
	Update_url	[]string	`json:"UPDATE_URL"`
	Revs	[]string	`json:"REVS"`
	Trust_point	string	`json:"TRUST_POINT"`
	Ikev1_user_auth_intfc	[]string	`json:"IKEV1_USER_AUTH_INTFC"`
	Ikev1_user_auth_type	[]string	`json:"IKEV1_USER_AUTH_TYPE"`
	Ikev2_local_auth_cert	string	`json:"IKEV2_LOCAL_AUTH_CERT"`
	Ikev2_remote_auth_type	[]string	`json:"IKEV2_REMOTE_AUTH_TYPE"`
	Peer_id_validate	string	`json:"PEER_ID_VALIDATE"`
	Radius_with_expiry	string	`json:"RADIUS_WITH_EXPIRY"`
	Ppp_auth_type	[]string	`json:"PPP_AUTH_TYPE"`
	Webvpn_auth	string	`json:"WEBVPN_AUTH"`
	Webvpn_custom	string	`json:"WEBVPN_CUSTOM"`
	Dns_grp	string	`json:"DNS_GRP"`
	Webvpn_grp_alias	[]string	`json:"WEBVPN_GRP_ALIAS"`
	Webvpn_grp_alias_state	[]string	`json:"WEBVPN_GRP_ALIAS_STATE"`
	Webvpn_grp_url	[]string	`json:"WEBVPN_GRP_URL"`
	Webvpn_grp_url_state	[]string	`json:"WEBVPN_GRP_URL_STATE"`
	Nbns_svr	[]string	`json:"NBNS_SVR"`
	Nbns_master	[]string	`json:"NBNS_MASTER"`
	Nbns_timeout	[]string	`json:"NBNS_TIMEOUT"`
	Nbns_retry	[]string	`json:"NBNS_RETRY"`
	Override_svc_download	string	`json:"OVERRIDE_SVC_DOWNLOAD"`
	Pri_prefill_user_type	[]string	`json:"PRI_PREFILL_USER_TYPE"`
	Sec_prefill_user_type	[]string	`json:"SEC_PREFILL_USER_TYPE"`
	Proxy_auth	string	`json:"PROXY_AUTH"`
	Radius_reject_msg	string	`json:"RADIUS_REJECT_MSG"`
	Saml_id_provider	string	`json:"SAML_ID_PROVIDER"`
	Without_csd	string	`json:"WITHOUT_CSD"`
}